-- Update blog_posts table for improved SEO and content uniqueness tracking

-- Add JSONB column for detailed SEO data
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS seo_data JSONB;

-- Add column for topic categorization 
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS category TEXT;

-- Add column for tracking content uniqueness score (higher is more unique)
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS uniqueness_score INTEGER DEFAULT 70;

-- Add column for content hash to quickly identify similar content
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS content_hash TEXT;

-- Add column for primary keyword
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS primary_keyword TEXT;

-- Add column for readability score
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS readability_score INTEGER DEFAULT 70;

-- Add column for cornerstone content flag
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS is_cornerstone BOOLEAN DEFAULT FALSE;

-- Add column for tracking if post was auto-generated
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS is_auto_generated BOOLEAN DEFAULT FALSE;

-- Add column for tracking generation model/version
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS generation_model TEXT;

-- Add column for tracking the generation date separately from created_at
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP WITH TIME ZONE;

-- Create index on tags for faster searches
CREATE INDEX IF NOT EXISTS idx_blog_posts_tags ON blog_posts USING GIN (tags);

-- Create index on primary_keyword for faster searches
CREATE INDEX IF NOT EXISTS idx_blog_posts_primary_keyword ON blog_posts (primary_keyword);

-- Create index on content_hash for duplicate detection
CREATE INDEX IF NOT EXISTS idx_blog_posts_content_hash ON blog_posts (content_hash);

-- Comment on new columns
COMMENT ON COLUMN blog_posts.seo_data IS 'Detailed SEO data in JSON format including keywords, meta tags, etc.';
COMMENT ON COLUMN blog_posts.category IS 'Primary category of the blog post for better organization';
COMMENT ON COLUMN blog_posts.uniqueness_score IS 'Score from 0-100 indicating content uniqueness';
COMMENT ON COLUMN blog_posts.content_hash IS 'Hash of main content for detecting similar content';
COMMENT ON COLUMN blog_posts.primary_keyword IS 'Main focus keyword for the article';
COMMENT ON COLUMN blog_posts.readability_score IS 'Score from 0-100 indicating content readability';
COMMENT ON COLUMN blog_posts.is_cornerstone IS 'Whether this is a cornerstone content piece';
COMMENT ON COLUMN blog_posts.is_auto_generated IS 'Whether this post was auto-generated by AI';
COMMENT ON COLUMN blog_posts.generation_model IS 'AI model used to generate this content';
COMMENT ON COLUMN blog_posts.generated_at IS 'When the content was generated (vs. when it was added to DB)';

-- Update existing posts to set sensible defaults for new columns
UPDATE blog_posts
SET 
    seo_data = jsonb_build_object(
        'keywords', tags,
        'focusKeyphrase', split_part(slug, '-', 1)
    ),
    primary_keyword = CASE 
        WHEN array_length(tags, 1) > 0 THEN tags[1]
        ELSE split_part(slug, '-', 1)
    END,
    readability_score = 70,
    uniqueness_score = 70,
    is_auto_generated = TRUE,
    generation_model = 'gemini-2.0-flash',
    generated_at = created_at;

-- Create function to automatically create content hash before insert/update
CREATE OR REPLACE FUNCTION generate_content_hash() 
RETURNS TRIGGER AS $$
BEGIN
    -- Create a hash of the first 1000 chars of content to detect similar posts
    -- md5 is used for speed, this is not for security purposes
    NEW.content_hash = md5(substring(NEW.content, 1, 1000));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update content_hash
DROP TRIGGER IF EXISTS update_blog_post_content_hash ON blog_posts;
CREATE TRIGGER update_blog_post_content_hash
BEFORE INSERT OR UPDATE OF content ON blog_posts
FOR EACH ROW 
EXECUTE FUNCTION generate_content_hash();
