import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { PageHeader } from '@/components/PageHeader';
import { getGalleryImages, ImageRecord } from '@/lib/supabase';

export const metadata = {
  title: 'Gallery | AI Coloring Page Generator',
  description: 'Browse through our collection of AI-generated coloring pages created by our community.',
};

export const revalidate = 3600; // Revalidate this page every hour

export default async function GalleryPage() {
  try {
    const images = await getGalleryImages(24);
    
    // Use sample images if database is not set up or returned no images
    const hasImages = images && images.length > 0;

    return (
      <div className="min-h-screen bg-gray-50">
        <PageHeader
          title="Coloring Page Gallery"
          description="Browse through our collection of AI-generated coloring pages created by our community."
        />

        <section className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
          <div className="mb-12 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Recent Creations</h2>
              <p className="mt-2 text-sm text-gray-600">
                Discover the latest coloring pages generated by our users
              </p>
            </div>
            <Link 
              href="/create" 
              className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              Create Your Own
            </Link>
          </div>

          {hasImages ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {images.map((image) => (
                <div 
                  key={image.id} 
                  className="bg-white rounded-lg shadow-md overflow-hidden transition-transform hover:shadow-lg hover:-translate-y-1"
                >
                  <div className="relative h-60 w-full">
                    <Image
                      src={image.image_url}
                      alt={image.title || image.prompt.substring(0, 50)}
                      fill
                      className="object-cover"
                      sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                      onError={(e) => {
                        console.error('Error loading gallery image:', image.image_url);
                        if (e.target instanceof HTMLImageElement) {
                          e.target.onerror = null; // Prevent infinite fallback loop
                          e.target.src = '/placeholder-image.svg'; // Fallback to a placeholder image
                        }
                      }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium text-gray-900 truncate">
                      {image.title || image.prompt.substring(0, 50)}
                    </h3>
                    <div className="mt-2 flex justify-between items-center">
                      <p className="text-sm text-gray-500">Style: {image.style || 'Standard'}</p>
                      <p className="text-sm text-gray-500">
                        {new Date(image.created_at).toLocaleDateString()}
                      </p>
                    </div>
                    <div className="mt-4 flex space-x-2">
                      <Link
                        href={`/gallery/${image.id}`}
                        className="flex-1 inline-flex justify-center items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                      >
                        View
                      </Link>
                      <Link
                        href={`/gallery/${image.id}/print`}
                        className="flex-1 inline-flex justify-center items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                      >
                        Print
                      </Link>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-16 bg-gray-50 rounded-lg">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-gray-400 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
              <h2 className="text-xl font-bold text-gray-700 mb-2">No images yet</h2>
              <p className="text-gray-600 mb-6">Be the first to add a coloring page to our gallery!</p>
              <Link 
                href="/create" 
                className="inline-flex items-center px-5 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                Create a Coloring Page
              </Link>
            </div>
          )}

          {hasImages && images.length >= 12 && (
            <div className="mt-12 text-center">
              <Link 
                href="/gallery?page=2"
                className="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                Load More
              </Link>
            </div>
          )}
        </section>
      </div>
    );
  } catch (error) {
    console.error('Error in Gallery Page:', error);
    // Return error UI
    return (
      <div className="min-h-screen bg-gray-50">
        <PageHeader
          title="Coloring Page Gallery"
          description="Browse through our collection of AI-generated coloring pages created by our community."
        />
        
        <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
          <div className="text-center py-16 bg-white rounded-lg shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-red-500 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <h2 className="text-xl font-bold text-gray-700 mb-2">Temporarily Unable to Load Gallery</h2>
            <p className="text-gray-600 mb-6">We're experiencing issues connecting to our image database. Please try again later.</p>
            <div className="flex justify-center space-x-4">
              <Link 
                href="/" 
                className="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                Return Home
              </Link>
              <Link 
                href="/create" 
                className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                Create a Coloring Page
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  }
} 